version: '3.3'

services:

  movie-list:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'

  cypress:
    build:
      context: .
      dockerfile: Dockerfile-cypress
    depends_on:
      - movie-list

